### ISSUE TITLE
transform names beginning with 'in'

### ISSUE THREAD

**Issue by will-weiss** [TechnologyAdvice/Jexl#2]
Adding a transform with a name beginning with 'in' causes the Lexer not to recognize the transform name as a token. For example,

<pre><code>
jexl.addTransform('indexOf', function(val, i) {
  return val.indexOf(i);
});

jexl.eval("[1,2,3] | indexOf(1)", {}).then(function(res) {
  console.log(res); // expecting 0
});

</code></pre>

fails because indexOf is tokenized as 'in' and 'dexOf'.

**Comment by TomFrost** [comment]
Great catch -- thanks for the bug report!

This is now fixed in 1.1.2, just pushed to npm. Please let me know if this doesn't resolve your issue.
