### ISSUE TITLE
Is it possible to get evaluation result synchronously?

### ISSUE THREAD

**Issue by Alex-Hagen-Thorn-at-Experieco** [TechnologyAdvice/Jexl#30]
Hi, 

I need to evaluate an expression, but I need the result immediately, not wrapped into a promise. The evaluator is executed in a synchronous context and I cannot switch to async pattern. All used variables are ready, no promises. 

Is this possible with the current version?

If not, are you planning to add this feature? How difficult is it to implement in current architecture, if I decide to add it by myself?

Thank you.

**Comment by Alex-Hagen-Thorn-at-Experieco** [comment]
Sorry, I did not notice the closed ticket addressing this. Now I see, that is not possible. OK (sigh)...

**Comment by TomFrost** [comment]
Indeed-- that response is still accurate. Sorry Jexl doesn't fit the synchronous use case!
